### ISSUE TITLE
浮动和定位实现常见布局

### ISSUE THREAD

**Issue by lwy1010** [lwy1010/BLOG#10]
###

### What

其实布局的本质就是一列上容纳多个块级元素。

### Why

网页的默认布局不能满足生产环境中复杂布局的需求。

#### 单列布局

单列布局时最简单的布局，通常会居中显示：

```html
<main></main>
```

```css
margin: 0 auto;
width: 600px;
height: 800px;
min-width: 480px;
```

#### 双列布局

双列布局很常见(一列负责显示广告等，另一列负责主题内容)。

一列定宽，一列自适应布局的实现：

```html
<main>
  <div class="left">left</div>
  <div class="right">right</div>
</main>
```

```css
main .left {
  float: left;
  width: 300px;
  background-color: red;
}

main .right {
  margin-left: 300px;
  background-color: green;
}
```

其实就是左栏设置 float，右栏的 margin-left 为左栏的宽度。

#### 三列布局

三列布局很常见，通常需求为左右两列定宽，中间列自适应剩余宽度，圣杯布局和双飞翼布局都是该需求的扩展物。

下面来看看一个左列宽度为 200px，中间列自适应，右列宽度为 220px 的圣杯布局和双飞翼布局是如何实现的：

圣杯布局:

```html
<div class="container">
  <!-- 内容优先渲染 -->
  <div class="middle">middle</div>
  <div class="left">left</div>
  <div class="right">right</div>
</div>
```

```css
.container {
  padding: 0 220px 0 200px;
}

.middle,
.left,
.right {
  float: left;
  position: relative;
}

.middle {
  width: 100%;
  background-color: green;
}

.left {
  width: 200px;
  margin-left: -100%;
  left: -200px;
  background-color: red;
}

.right {
  width: 220px;
  margin-left: -220px;
  right: -220px;
  background-color: blue;
}
```

双飞翼布局:

```html
<div class="container">
  <div class="middle">
    <div class="middle-inner">middle</div>
  </div>
  <div class="left">left</div>
  <div class="right">right</div>
</div>
```

```css
.middle,
.left,
.right {
  float: left;
}

.middle {
  width: 100%;
  background-color: green;
}

.middle .middle-inner {
  margin: 0 -220px 0 200px;
}

.left {
  width: 200px;
  margin-left: -100%;
  background-color: red;
}

.right {
  width: 220px;
  margin-left: -220px;
  background-color: blue;
}
```

圣杯布局与双飞翼布局的区别在于双飞翼布局的中间容器 middle 多了一个子容器存在，然后通过控制 middle 的子容器的 margin 或者 padding 空出左右两列的宽度而无需使用相对定位特性。个人觉得后者相对简单一点。
