### ISSUE TITLE
flex布局简明笔记

### ISSUE THREAD

**Issue by lwy1010** [lwy1010/BLOG#11]
### What

Flex 布局是一种高效灵活的布局方式。

### Why

在 flex 之前，我们通常使用浮动和定位来实现网页布局，但很多时候，使用浮动和定位来进行网页布局不够优雅和灵活，如等高、垂直居中、剩余宽度等问题。由此，Flex 的出现使布局给更加的简单和灵活。

### How

要使用 flex 布局，只要在父容器(container)中设置 display: flex 即可，这样容器中的子元素自动成为容器的子项目(item)，然后就可以使用 flex 的相关属性来控制项目行为了。

在开始实战之前还是先来理解 flex 的基本概念：

![19601](https://github.com/lwy1010/mdPic/blob/master/19601-flex_terms.png?raw=true)

- flex 容器(container)中存在两根轴——主轴(main axis)和交叉轴(cross axis)，值得注意的是，不能认为水平方向就是主轴，垂直方向的为交叉轴。

- 每根轴存在着起始位置和终点位置——水平方向从左到右(main start -> main end)，垂直方向从上到下(cross start -> cross end)

- 项目(item)占据占据主轴的空间为 main size，占据的交叉轴空间叫做 cross size。

接下来看看与 flex 相关的属性：

#### 由父元素控制的属性：

- flex-direction：控制主轴的方向(默认水平方向)。

- flex-wrap：控制项目的换行方式(默认不换行，空间不足时，自动调整自身大小)。

- justify-content：控制主轴上项目的对齐方式(默认左对齐)。

- align-items：控制交叉轴上项目的对齐方式(默认与容器同高，即在项目未设置高度或设为 auto 时)。

- align-content：控制多根交叉轴(如通过 flex-wrap 换行后)的对齐方式(若容器内只有一根交叉轴时，属性不起作用)。

#### 作用在子元素自身的属性：

- order：控制项目在容器的排列顺序(默认为 0,数值越小，排列越靠前)。

- flex-basis：控制项目的主轴空间的大小(默认为 auto,即项目本身的大小)。

- flex-grow：存在剩余空间时，控制项目放大的比例(默认为 0，不放大)。

- flex-shrink：容器空间不足时，控制项目的缩小比例(默认为 1，容器空间不足时，所有项目等比列缩小，可通过设置更小的值控制自身不缩小)。

- align-self：单独控制(会覆盖 align-items 属性)项目在交叉轴上的对齐方式(默认值为 auto，即继承父元素的 align-items 属性)。

- flex：flex-grow, flex-shrink 和 flex-basis 的简写(默认值为 0 1 atuo)。

#### 实战

下面利用上面的 flex 知识来实现垂直居中、一列定宽一列自适应布局和圣杯布局。

垂直居中：

```html
<div class="container">
  <div class="item">item</div>
</div>
```

```css
.container {
  display: flex;
  justify-content: center;
  align-items: center;
}
```

一列定宽一列自适应：

```html
<div class="container">
  <div class="left">left</div>
  <div class="right">right</div>
</div>
```

```css
.container {
  display: flex;
}
.left {
  width: 220px;
}
.right {
  flex: 1;
}
```

圣杯布局：

```html
<div class="container">
  <div class="middle">middle</div>
  <div class="left">left</div>
  <div class="right">right</div>
</div>
```

```css
.container {
  display: flex;
}
.middle {
  order: 2;
  flex: 1 0 auto;
}
.left {
  order: 1;
  flex: 0 1 200px;
}
.right {
  order: 3;
  flex: 0 1 220px;
}
```
