### ISSUE TITLE
谈谈CSS水平和垂直居中方法

### ISSUE THREAD

**Issue by lwy1010** [lwy1010/BLOG#12]
### What

使一个行内或者块级元素水平或垂直居中，在 CSS 日常编码中非常常见。

### Why

掌握常见的水平垂直居中有利于日常的 CSS 的编写，而且这知识点面试几乎必考。

### How

为了防止文章的边幅过长，只给出关键代码。

#### 行内元素

HTML:

```html
<div class="container">
  <span>box</span>
</div>
```

CSS:

水平居中：

```css
.container {
  text-align: center;
}
```

垂直居中：

```css
.container {
  height: 480px;
  line-height: 480px;
}
```

#### 块级元素

HTML:

```html
<div class="container">
  <div class="child">box</div>
</div>
```

CSS:

水平居中：

- 方式一：

  ```css
  .child {
    margin: 0 auto;
  }
  ```

- 方式二：

  ```css
  .container {
    position: relative;
  }

  .child {
    position: absolute;
    left: 50%;
    transform: translate(-50%, 0);
  }
  ```

- 方式三：

  ```css
  .container {
    display: flex;
    justify-content: center;
  }
  ```

垂直居中：

- 方式一：

  ```css
  .container {
    position: relative;
  }

  .child {
    position: absolute;
    top: 50%;
    transform: translate(0, -50%);
  }
  ```

- 方式二：

  ```css
  .container {
    display: flex;
    align-items: center;
  }
  ```

其实，方法是多种多样的，以上只是列举了些常见的解决方法。
