### ISSUE TITLE
响应式 Web 设计简易指南

### ISSUE THREAD

**Issue by lwy1010** [lwy1010/BLOG#13]
### What

响应式 Web 设计是一种可以在不同大小的设备上良好地呈现网页内容的一种方式。

### Why

希望网站能通过响应用户的行为、设备屏幕的大小和屏幕的方向，从而在所有设备上良好呈现。

### How

如今，响应式的网站非常常见，你可以访问如[Bootstrap](https://getbootstrap.com/)的官网，通过不断缩小浏览器的窗口宽度来查看网站内容的表现以获得对响应式设计的基本的感性认识。

那么在谈论响应式设计的时候，我们通常在讨论什么？

#### 媒体查询(media query)

媒体查询可以根据设备的特性（例如：尺寸、分辨率、宽高比、颜色位深等）来应用不同的样式。

```css
/* 小型设备屏幕 (默认) */
html {
  font-size: 100%;
}

/* 中型设备屏幕 (640px) */
@media (min-width: 40rem) {
  html {
    font-size: 112%;
  }
}
```

以上媒体查询会在屏幕分辨率不小于 640px 时，将整个网页的字体的大小扩大 1.12 倍。

#### 流体布局(fluid grid)

流体布局也叫做百分比布局、弹性盒布局，它使用百分比来设定容器的宽度，从而使容器在浏览器窗口大小变化时自动缩放。

#### 一些最佳实践的建议

- 使用相对单位，如 rem、em 而不是 绝对单位px。

- 使用 border-box 盒模型来代替 默认的content-box盒模型。

- 使用 Normalize.css 来统一不同浏览器的显示。

### 实战练习

关键代码如下：

```html
<div class="container">
  <div class="row">
    <div class="col">col1</div>
    <div class="col">col2</div>
  </div>
</div>
```

```css
* {
  box-sizing: border-box;
}
.container {
  width: 100%;
}
.row {
  display: flex;
  flex-wrap: wrap;
}
/*列的宽度随浏览器窗口宽度的大小自动缩放*/
.col {
  width: 50%;
}
/* 默认行中两列并行显示，当屏幕宽度小于640px时，列换行显示*/
@media (max-width: 40rem) {
  .col {
    width: 100%;
  }
}
```
