### ISSUE TITLE
SASS快速上手指南

### ISSUE THREAD

**Issue by lwy1010** [lwy1010/BLOG#17]
### What

[SASS](https://sass-lang.com/guide)是一种 CSS 的扩展语言，它拥有变量、嵌套、继承等强大功能，这大大提高了编写 CSS 代码的效率而且代码更利于阅读。

### Why

在编写 CSS 代码的时候，我们其实很多时间浪费在重复写选择器和某些样式规则上，因为 CSS 没有变量(已有，兼容不好)、嵌套、继承等特性，一些 CSS 规则无法得到复用，而 SASS 作为 CSS 的扩展语言解决了这样问题，我们通过使用 SASS 的强大语法来编写样式，最后编译成 CSS 的代码即可。

#### 安装

对于编译工具，我这里使用的是 node-sass，通过 yarn 来全局安装：

```
yarn global add node-sass
```

如果安装失败，请设置 sass-binary 的源为淘宝源即可：

```
yarn config set sass-binary-site http://npm.taobao.org/mirrors/node-sass
```

最后检查是否安装成功：

```
node-sass -v
```

#### node-sass 的使用

新建个.scss 文件，内容为：

```scss
$blue: #007bff;

div {
  color: $blue;
}
```

使用命令编译 SASS：

```
node-sass -w index.scss index.css --output-style expanded
```

以上命令表示在监听 index.scss 的变化，当保存 index.scss 时在其同级目录下输出风格为 expanded 的 index.css。这样在网页中引入 index.css 的文件后，使用 sass 语法来编写样式时能实时同步到网页上，简单快捷。

#### 语法

有了上面的简单准备，是时候来感受 SASS 的强大了。为了减少文章边幅，以下并没有给出 SASS 代码编译后的 CSS 效果，请自行编译查看。

##### 变量

SASS 通过\$来定义变量，你可以把一些网页中重复使用的颜色、字体及大小等东西存储到变量从而复用这些样式：

```scss
$blue: #007bff;
$font-stack: Helvetica, sans-serif;

div {
  color: $blue;
  font: $font-stack;
}
```

##### 嵌套

嵌套可以大大减少我们重复编写选择器，而且代码更加易读。

```scss
nav {
  a {
    text-decoration: none;
    &:hover {
      color: aqua;
    }
  }
}
```

其中在使用伪类时，父元素可以通过&来表示。

##### Mixins

Mixins 的功能可以重复使用某个选择器的样式，使用@mixin 定义，@include 调用。

```scss
@mixin ol-box {
  outline: 1px solid white;
}
@mixin pd-left($value: 10px) {
  padding: $value;
}
div {
  background-color: aqua;
  @include ol-box;
  @include pd-left(20px);
}
```

##### 继承

继承的功能可以继承另一个选择器的样式，实用@extend 来继承。

```scss
.message {
  border: 1px solid #ccc;
  padding: 10px;
  color: #333;
}
.message-success {
  @extend .message;
  border-color: green;
}
```

##### 运算符

在规则中也可以使用如+、-、 \*、 %等数学运算

```scss
.container {
  width: 100%;
}

article[role='main'] {
  float: left;
  width: 600px / 960px * 100%;
}
```

最后，SASS 的功能还有条件、循环等等，上面只是列举出常用的一部分，更多语法请参考文末的链接。

### MORE

- [sass](https://sass-lang.com)
- [node-sass](https://github.com/sass/node-sass)
